"""
Intersect — Safe Allowlisted SymPy Expression Builder and Exact Intersection Engine (Phase V4)

Security & Architecture Guarantees:
1. Zero eval(), exec(), or arbitrary code generation from user input.
2. Accepts ONLY declarative JSON construction steps generated by the V2 TypeScript pipeline.
3. Every operation, symbol, and constant is verified against a strict finite allowlist.
4. All symbols are instantiated with real=True to enforce real-valued geometry.
5. Real root semantics: Odd roots of negative bases evaluate to real numbers via sp.real_root.
6. Domain obligations and equations are preserved separately from automatic simplifications.
7. Pure JSON-serializable outputs; PyProxy objects must be destroyed in JS callers.
8. Bounded Portfolio of General Symbolic Strategies:
   - Safe preprocessing, trivial contradiction & degeneracy detection
   - Linear systems (affine planes intersection, lines, coincident 2D overlap)
   - Plane-conic and structured quadric strategies (plane-sphere, cylinder-plane)
   - Quadric-quadric reduction (elimination of shared quadratic parts to plane-conic)
   - Coordinate parameterization & substitution (x=t, y=t, z=t with domain and box clipping)
   - Rigorous candidate certification, deterministic ranking, and transformation recording
"""

import json
import math
import time
import sympy as sp

# Supported constant mapping
ALLOWED_CONSTANTS = {
    'pi': sp.pi,
    'E': sp.E,
}

# Allowlisted symbol names for Cartesian coordinates and parameter
x, y, z = sp.symbols('x y z', real=True)
t = sp.Symbol('t', real=True)

ALLOWED_SYMBOLS = {'x': x, 'y': y, 'z': z, 't': t}

DEFAULT_BOUNDS = {
    'minX': -1000, 'maxX': 1000,
    'minY': -1000, 'maxY': 1000,
    'minZ': -1000, 'maxZ': 1000
}


def normalize_bounds(b):
    if isinstance(b, dict):
        return [
            b.get('xMin', b.get('minX', -1000)),
            b.get('xMax', b.get('maxX', 1000)),
            b.get('yMin', b.get('minY', -1000)),
            b.get('yMax', b.get('maxY', 1000)),
            b.get('zMin', b.get('minZ', -1000)),
            b.get('zMax', b.get('maxZ', 1000)),
        ]
    return list(b)


def build_step(step):
    """
    Recursively constructs a SymPy expression tree from a validated SymPyConstructionStep.
    Raises ValueError on any unsupported operator or invalid structure.
    """
    if not isinstance(step, dict):
        raise ValueError(f"Invalid construction step: expected dict, got {type(step).__name__}")

    op = step.get('op')
    if not op or not isinstance(op, str):
        raise ValueError("Construction step missing 'op' property")

    if op == 'Integer':
        val_str = str(step.get('value', '0'))
        return sp.Integer(int(val_str))

    elif op == 'Rational':
        num_str = str(step.get('num', '0'))
        den_str = str(step.get('den', '1'))
        den = int(den_str)
        if den == 0:
            raise ValueError("Zero denominator in Rational construction step")
        return sp.Rational(int(num_str), den)

    elif op == 'Symbol':
        name = step.get('name')
        if not isinstance(name, str) or name not in ALLOWED_SYMBOLS:
            raise ValueError(f"Disallowed or unknown symbol: {name}")
        return ALLOWED_SYMBOLS[name]

    elif op == 'Constant':
        name = step.get('name')
        if not isinstance(name, str) or name not in ALLOWED_CONSTANTS:
            raise ValueError(f"Disallowed or unknown constant: {name}")
        return ALLOWED_CONSTANTS[name]

    # Operator node handling
    args_raw = step.get('args')
    if not isinstance(args_raw, list):
        raise ValueError(f"Operator step '{op}' must contain 'args' list")

    args = [build_step(a) for a in args_raw]

    if op == 'Add':
        return sp.Add(*args)

    elif op == 'Mul':
        return sp.Mul(*args)

    elif op == 'Pow':
        if len(args) != 2:
            raise ValueError(f"Pow operator requires exactly 2 arguments, got {len(args)}")
        base, exp = args[0], args[1]
        # Real root compatibility:
        # SymPy's default sp.Pow(-8, 1/3) evaluates to complex 1 + sqrt(3)*I on the principal branch.
        # In real-valued geometry, an odd root of a real number is uniquely real.
        if isinstance(exp, sp.Rational) and exp.q % 2 != 0:
            return sp.real_root(base, exp.q) ** exp.p
        return sp.Pow(base, exp)

    elif op == 'Sqrt':
        if len(args) != 1:
            raise ValueError(f"Sqrt operator requires exactly 1 argument, got {len(args)}")
        return sp.sqrt(args[0])

    elif op == 'Root':
        if len(args) != 2:
            raise ValueError(f"Root operator requires exactly 2 arguments (radicand, index), got {len(args)}")
        radicand, index = args[0], args[1]
        if isinstance(index, sp.Integer) and index % 2 != 0:
            return sp.real_root(radicand, int(index))
        elif isinstance(index, sp.Rational) and index.p % 2 != 0:
            inv = sp.Pow(index, -1)
            if isinstance(inv, sp.Rational) and inv.q % 2 != 0:
                return sp.real_root(radicand, inv.q) ** inv.p
        return sp.Pow(radicand, sp.Pow(index, -1))

    elif op == 'Abs':
        if len(args) != 1:
            raise ValueError("Abs operator requires exactly 1 argument")
        return sp.Abs(args[0])

    elif op == 'Sin':
        return sp.sin(args[0])
    elif op == 'Cos':
        return sp.cos(args[0])
    elif op == 'Tan':
        return sp.tan(args[0])
    elif op == 'Sec':
        return sp.sec(args[0])
    elif op == 'Csc':
        return sp.csc(args[0])
    elif op == 'Cot':
        return sp.cot(args[0])

    elif op == 'ArcSin':
        return sp.asin(args[0])
    elif op == 'ArcCos':
        return sp.acos(args[0])
    elif op == 'ArcTan':
        return sp.atan(args[0])

    elif op == 'Sinh':
        return sp.sinh(args[0])
    elif op == 'Cosh':
        return sp.cosh(args[0])
    elif op == 'Tanh':
        return sp.tanh(args[0])

    elif op == 'Exp':
        return sp.exp(args[0])
    elif op == 'Log':
        return sp.log(args[0])

    elif op == 'Eq':
        if len(args) != 2:
            raise ValueError("Eq operator requires exactly 2 arguments")
        return sp.Eq(args[0], args[1])

    else:
        raise ValueError(f"Unsupported construction operator: '{op}'")


def build_surface(plan):
    """
    Constructs SymPy objects for a single surface plan, producing serializable summary data.
    """
    if not isinstance(plan, dict):
        raise ValueError("Surface plan must be a dict")

    target = plan.get('target')
    if target != 'sympy':
        raise ValueError(f"Unsupported plan target: {target}")

    eq_step = plan.get('equation')
    if not eq_step or eq_step.get('op') != 'Eq':
        raise ValueError("Invalid equation step: expected Eq relation")

    lhs_expr = build_step(eq_step['args'][0])
    rhs_expr = build_step(eq_step['args'][1])
    equation = sp.Eq(lhs_expr, rhs_expr)

    residual = lhs_expr - rhs_expr
    simplified_residual = sp.simplify(residual)

    free_syms = sorted([s.name for s in residual.free_symbols if isinstance(s, sp.Symbol)])
    symbols_sp = [ALLOWED_SYMBOLS[name] for name in free_syms if name in ALLOWED_SYMBOLS]

    raw_conditions = plan.get('domainConditions', [])
    domain_conditions = []
    for cond in raw_conditions:
        c_step = cond.get('condition')
        c_expr = build_step(c_step) if c_step else None
        kind = cond.get('kind', 'unknown')
        c_str = str(c_expr) if c_expr is not None else ''

        domain_conditions.append({
            'id': cond.get('id', ''),
            'kind': kind,
            'conditionStr': c_str,
            'description': cond.get('description', ''),
        })

    is_poly = False
    degree = None
    if symbols_sp:
        try:
            is_poly = bool(residual.is_polynomial(*symbols_sp))
            if is_poly:
                degree = int(sp.total_degree(residual, *symbols_sp))
        except Exception:
            is_poly = False
            degree = None
    elif residual.is_number:
        is_poly = True
        degree = 0

    is_identity = bool(residual == 0 or simplified_residual == 0)
    is_contradiction = bool(residual.is_number and residual != 0)

    return {
        'equationStr': str(equation),
        'lhsStr': str(lhs_expr),
        'rhsStr': str(rhs_expr),
        'residualStr': str(residual),
        'simplifiedResidualStr': str(simplified_residual),
        'variables': free_syms,
        'domainConditions': domain_conditions,
        'isPolynomial': is_poly,
        'degree': degree,
        'isConstantIdentity': is_identity,
        'isConstantContradiction': is_contradiction,
    }


def prepare_system_json(json_str):
    """
    Main entry point for Phase V3 expression analysis.
    """
    data = json.loads(json_str)
    plan_f = data.get('surfaceF')
    plan_g = data.get('surfaceG')

    if not plan_f or not plan_g:
        raise ValueError("Payload must contain both 'surfaceF' and 'surfaceG' plans")

    res_f = build_surface(plan_f)
    res_g = build_surface(plan_g)

    joint_vars = sorted(list(set(res_f['variables']).union(set(res_g['variables']))))
    total_domain_conds = len(res_f['domainConditions']) + len(res_g['domainConditions'])
    has_identity = res_f['isConstantIdentity'] or res_g['isConstantIdentity']
    has_contradiction = res_f['isConstantContradiction'] or res_g['isConstantContradiction']

    summary = {
        'surfaceF': res_f,
        'surfaceG': res_g,
        'systemVariables': joint_vars,
        'totalDomainObligations': total_domain_conds,
        'hasIdentity': has_identity,
        'hasContradiction': has_contradiction,
    }

    return json.dumps(summary)


# ==============================================================================
# Phase V4: Exact Intersection Engine Helpers & Strategies
# ==============================================================================

def safe_numeric_approx(expr):
    """Safely converts exact expression to float approximation."""
    try:
        val = float(expr.evalf())
        if math.isnan(val) or math.isinf(val):
            return None
        return val
    except Exception:
        return None

def make_finite_endpoint(expr, approx=None):
    if approx is None:
        approx = safe_numeric_approx(expr)
    return {
        'kind': 'finite',
        'exact': str(expr),
        'numericApprox': approx
    }

def make_infinite_endpoint(sign):
    return {
        'kind': 'infinite',
        'sign': sign
    }

def make_interval(min_ep, min_inc, max_ep, max_inc):
    return {
        'min': min_ep,
        'minInclusive': min_inc if min_ep['kind'] == 'finite' else False,
        'max': max_ep,
        'maxInclusive': max_inc if max_ep['kind'] == 'finite' else False,
    }


def is_sum_of_squares_positive(expr):
    """
    Checks if an expression is of the form sum(c_i * (x_i - p_i)^2) + K
    with c_i > 0 and K > 0 in real variables, which proves real emptiness.
    Returns (True, K, parts) or ('zero', 0, parts) or (False, None, None).
    """
    try:
        expr_exp = sp.expand(expr)
        free = [s for s in expr_exp.free_symbols if s in {x, y, z}]
        if not free:
            if expr_exp.is_number and expr_exp > 0:
                return True, expr_exp, []
            return False, None, None

        if not expr_exp.is_polynomial(*free):
            return False, None, None

        for i in range(len(free)):
            for j in range(i + 1, len(free)):
                if expr_exp.coeff(free[i] * free[j]) != 0:
                    return False, None, None

        parts = []
        c0 = expr_exp.subs([(v, 0) for v in free])
        sum_subtracted = sp.Integer(0)
        for var in free:
            a = expr_exp.coeff(var, 2)
            b = expr_exp.coeff(var, 1)
            if a <= 0:
                return False, None, None
            p = -sp.Rational(b, 2*a) if isinstance(b, sp.Integer) and isinstance(a, sp.Integer) else -b / (2*a)
            parts.append((a, var, p))
            sum_subtracted += a * p**2

        const_term = sp.simplify(c0 - sum_subtracted)
        if const_term.is_number and const_term > 0:
            return True, const_term, parts
        elif const_term.is_number and const_term == 0:
            return 'zero', const_term, parts
    except Exception:
        pass
    return False, None, None


def check_trivial_emptiness_or_degeneracy(F_res, G_res, bounds):
    """
    Detects constant contradictions, constant identities, and sum of squares contradictions.
    """
    if F_res.is_number and F_res != 0:
        return {
            'status': 'empty-bounded',
            'bounds': bounds,
            'reasonCode': 'algebraic_contradiction',
            'proofScope': 'global',
            'proofExplanation': f'Proved no real intersection exists globally in R^3: Surface F equation is an algebraic contradiction ({F_res} = 0).'
        }
    if G_res.is_number and G_res != 0:
        return {
            'status': 'empty-bounded',
            'bounds': bounds,
            'reasonCode': 'algebraic_contradiction',
            'proofScope': 'global',
            'proofExplanation': f'Proved no real intersection exists globally in R^3: Surface G equation is an algebraic contradiction ({G_res} = 0).'
        }

    if F_res == 0 and G_res == 0:
        return {
            'status': 'degenerate',
            'nature': 'coincident-surfaces',
            'message': 'Both equations are constant identities; intersection is all of space.',
            'explanation': 'Both surfaces are identically satisfied everywhere; intersection is three-dimensional space.'
        }

    # Sum of squares strictly positive
    is_pos_f, k_f, _ = is_sum_of_squares_positive(F_res)
    if is_pos_f is True:
        return {
            'status': 'empty-bounded',
            'bounds': bounds,
            'reasonCode': 'sum_of_squares_positive',
            'proofScope': 'global',
            'proofExplanation': 'Proved no real intersection exists globally in R^3: Surface F requires a sum of real squares to equal a negative number, having no real solutions.'
        }
    is_pos_g, k_g, _ = is_sum_of_squares_positive(G_res)
    if is_pos_g is True:
        return {
            'status': 'empty-bounded',
            'bounds': bounds,
            'reasonCode': 'sum_of_squares_positive',
            'proofScope': 'global',
            'proofExplanation': 'Proved no real intersection exists globally in R^3: Surface G requires a sum of real squares to equal a negative number, having no real solutions.'
        }

    return None


def test_identity_numerically(expr, intervals=None):
    """
    Numerically tests whether expr evaluates to zero at multiple interior points
    within the parameter domain intervals. Used as a safe fallback when purely
    symbolic algebraic simplification does not reduce transcendental compositions.
    """
    try:
        test_pts = []
        if intervals:
            for iv in intervals[:3]:
                min_n = safe_numeric_approx(sp.sympify(iv['min']['exact'], locals=ALLOWED_SYMBOLS)) if iv['min']['kind'] == 'finite' else -10.0
                max_n = safe_numeric_approx(sp.sympify(iv['max']['exact'], locals=ALLOWED_SYMBOLS)) if iv['max']['kind'] == 'finite' else 10.0
                if min_n is not None and max_n is not None:
                    span = max_n - min_n
                    test_pts.extend([min_n + span * 0.15, min_n + span * 0.42, min_n + span * 0.73, min_n + span * 0.88])
        if not test_pts:
            test_pts = [0.15, 0.42, 1.25, 2.71, -0.63]
        for pt in test_pts:
            val = expr.subs(t, pt).evalf()
            if abs(complex(val)) > 1e-6:
                return False
        return True
    except Exception:
        return False


def is_closed_variety_check(F_res, G_res):
    """
    Detects whether the algebraic variety contains a closed loop component,
    such as when either surface is an elliptic/circular cylinder or a sphere,
    or when eliminating a variable yields an elliptic cylinder.
    """
    if is_sphere_check(F_res)[0] or is_sphere_check(G_res)[0]:
        return True
    if is_cylinder_check(F_res)[0] or is_cylinder_check(G_res)[0]:
        return True
    for v in (x, y, z):
        if F_res.is_polynomial(v) and sp.degree(F_res, v) == 1:
            try:
                v_sol = sp.solve(F_res, v)[0]
                G_elim = G_res.subs(v, v_sol)
                if is_cylinder_check(G_elim)[0] or is_sphere_check(G_elim)[0]:
                    return True
            except Exception:
                pass
        if G_res.is_polynomial(v) and sp.degree(G_res, v) == 1:
            try:
                v_sol = sp.solve(G_res, v)[0]
                F_elim = F_res.subs(v, v_sol)
                if is_cylinder_check(F_elim)[0] or is_sphere_check(F_elim)[0]:
                    return True
            except Exception:
                pass
    return False


def determine_parameter_domain(rx, ry, rz, is_periodic=False, domain_conds=None, bounds=DEFAULT_BOUNDS):
    """
    Phase 4: Exact Parameter Domain Determination (Rule 2).
    Calculates the true real parameter domain D of t.
    Considers even-root radicands (rad >= 0), denominators (den != 0),
    logarithms (arg > 0), inverse trig restrictions, and calculation bounds.
    Never defaults blindly to R.
    For periodic closed curves, returns the fundamental period [0, 2*pi) (Rule 6).
    """
    if domain_conds is None:
        domain_conds = []
    bounds = normalize_bounds(bounds)
    b_min_x, b_max_x, b_min_y, b_max_y, b_min_z, b_max_z = bounds

    if is_periodic:
        # Periodic curve: fundamental period [0, 2*pi)
        forbidden_pts = set()
        for expr in (rx, ry, rz):
            for part in expr.atoms(sp.Pow):
                if part.exp.is_negative:
                    try:
                        roots = sp.solve(part.base, t)
                        for r_ in roots:
                            if r_.is_real:
                                r_num = safe_numeric_approx(r_)
                                if r_num is not None and 0 <= r_num < 2 * math.pi:
                                    forbidden_pts.add(r_)
                    except Exception:
                        pass
            frac_den = sp.fraction(expr)[1]
            if frac_den != 1:
                try:
                    roots = sp.solve(frac_den, t)
                    for r_ in roots:
                        if r_.is_real:
                            r_num = safe_numeric_approx(r_)
                            if r_num is not None and 0 <= r_num < 2 * math.pi:
                                forbidden_pts.add(r_)
                except Exception:
                    pass

        for cond in domain_conds:
            c_expr = cond.get('expr')
            if c_expr is not None:
                c_sub = c_expr.subs([(x, rx), (y, ry), (z, rz)])
                try:
                    roots = sp.solve(c_sub, t)
                    for r_ in roots:
                        if r_.is_real:
                            r_num = safe_numeric_approx(r_)
                            if r_num is not None and 0 <= r_num < 2 * math.pi:
                                forbidden_pts.add(r_)
                except Exception:
                    pass

        if not forbidden_pts:
            return [make_interval(
                make_finite_endpoint(sp.Integer(0), 0.0), True,
                make_finite_endpoint(2 * sp.pi, 2 * math.pi), False
            )], "0 <= t < 2*pi"

        sorted_pts = sorted(list(forbidden_pts), key=lambda p: float(p.evalf()))
        intervals = []
        cur_min = sp.Integer(0)
        cur_min_inc = True
        for pt in sorted_pts:
            if pt == cur_min:
                cur_min_inc = False
                continue
            intervals.append(make_interval(
                make_finite_endpoint(cur_min), cur_min_inc,
                make_finite_endpoint(pt), False
            ))
            cur_min = pt
            cur_min_inc = False
        intervals.append(make_interval(
            make_finite_endpoint(cur_min), cur_min_inc,
            make_finite_endpoint(2 * sp.pi, 2 * math.pi), False
        ))
        return intervals, "0 <= t < 2*pi with singularities excluded"

    # Non-periodic curve
    t_min = sp.Integer(-1000)
    t_max = sp.Integer(1000)

    # 1. Bounds clipping from coordinates
    is_hyperbola_1_over_t = False
    for expr in (rx, ry, rz):
        if expr == t**2 or (isinstance(expr, sp.Pow) and expr.exp == 2 and expr.base == t):
            t_min = sp.Max(t_min, -sp.sqrt(1000))
            t_max = sp.Min(t_max, sp.sqrt(1000))
        elif isinstance(expr, sp.exp) and expr.args[0] == t:
            t_max = sp.Min(t_max, sp.log(1000))
        elif expr == 1/t or expr == sp.Pow(t, -1):
            is_hyperbola_1_over_t = True
        elif expr.is_polynomial(t) and sp.degree(expr, t) == 1:
            a_c = expr.coeff(t, 1)
            b_c = expr.subs(t, 0)
            if a_c > 0:
                t_min = sp.Max(t_min, (-1000 - b_c)/a_c)
                t_max = sp.Min(t_max, (1000 - b_c)/a_c)
            elif a_c < 0:
                t_min = sp.Max(t_min, (1000 - b_c)/a_c)
                t_max = sp.Min(t_max, (-1000 - b_c)/a_c)

    # 2. Even roots / Radicands
    radicands = []
    for expr in (rx, ry, rz):
        for part in expr.atoms(sp.Pow):
            if isinstance(part.exp, sp.Rational) and part.exp.q % 2 == 0:
                radicands.append(part.base)
            elif part.exp == sp.Rational(1, 2) or part.exp == 0.5:
                radicands.append(part.base)

    intervals_sp = [(t_min, t_max)]

    for rad in radicands:
        new_intervals = []
        for iv_start, iv_end in intervals_sp:
            start_num = safe_numeric_approx(iv_start)
            end_num = safe_numeric_approx(iv_end)
            if start_num is None or end_num is None or start_num >= end_num:
                continue

            try:
                roots = sp.solve(rad, t)
                real_roots = []
                for r_ in roots:
                    if r_.is_real:
                        r_n = safe_numeric_approx(r_)
                        if r_n is not None and start_num < r_n < end_num:
                            real_roots.append((r_n, r_))
                real_roots.sort(key=lambda x: x[0])
            except Exception:
                real_roots = []

            cuts = [iv_start] + [r[1] for r in real_roots] + [iv_end]
            for i in range(len(cuts) - 1):
                c1, c2 = cuts[i], cuts[i+1]
                mid = (c1 + c2) / 2
                try:
                    val = float(rad.subs(t, mid).evalf())
                    if val >= -1e-9:
                        new_intervals.append((c1, c2))
                except Exception:
                    pass
        intervals_sp = new_intervals

    if not intervals_sp:
        return [], "Empty domain"

    # 3. Forbidden points (singularities / denominators / domain conditions)
    forbidden_points = set()
    for expr in (rx, ry, rz):
        for part in expr.atoms(sp.Pow):
            if part.exp.is_negative:
                try:
                    roots = sp.solve(part.base, t)
                    for r_ in roots:
                        if r_.is_real: forbidden_points.add(r_)
                except Exception: pass
        frac_den = sp.fraction(expr)[1]
        if frac_den != 1:
            try:
                roots = sp.solve(frac_den, t)
                for r_ in roots:
                    if r_.is_real: forbidden_points.add(r_)
            except Exception: pass

    for cond in domain_conds:
        c_expr = cond.get('expr')
        if c_expr is not None:
            c_sub = c_expr.subs([(x, rx), (y, ry), (z, rz)])
            try:
                roots = sp.solve(c_sub, t)
                for r_ in roots:
                    if r_.is_real: forbidden_points.add(r_)
            except Exception: pass

    final_intervals = []
    if is_hyperbola_1_over_t:
        int1 = make_interval(
            make_finite_endpoint(-1000, -1000.0), True,
            make_finite_endpoint(sp.Rational(-1, 1000), -0.001), True
        )
        int2 = make_interval(
            make_finite_endpoint(sp.Rational(1, 1000), 0.001), True,
            make_finite_endpoint(1000, 1000.0), True
        )
        final_intervals = [int1, int2]
        desc = "[-1000, -0.001] U [0.001, 1000]"
    else:
        for iv_start, iv_end in intervals_sp:
            s_num = safe_numeric_approx(iv_start)
            e_num = safe_numeric_approx(iv_end)
            if s_num is None or e_num is None: continue
            pts_in_iv = sorted([p for p in forbidden_points if s_num < safe_numeric_approx(p) < e_num], key=lambda p: float(p.evalf()))
            if not pts_in_iv:
                final_intervals.append(make_interval(
                    make_finite_endpoint(iv_start), True,
                    make_finite_endpoint(iv_end), True
                ))
            else:
                cur_min = iv_start
                cur_min_inc = True
                for pt in pts_in_iv:
                    final_intervals.append(make_interval(
                        make_finite_endpoint(cur_min), cur_min_inc,
                        make_finite_endpoint(pt), False
                    ))
                    cur_min = pt
                    cur_min_inc = False
                final_intervals.append(make_interval(
                    make_finite_endpoint(cur_min), cur_min_inc,
                    make_finite_endpoint(iv_end), True
                ))
        desc = ', '.join(f"[{iv['min']['exact']}, {iv['max']['exact']}]" for iv in final_intervals)

    return final_intervals, desc
