"""
Intersect — Safe Allowlisted SymPy Expression Builder and Exact Intersection Engine (Phase V4)

Security & Architecture Guarantees:
1. Zero eval(), exec(), or arbitrary code generation from user input.
2. Accepts ONLY declarative JSON construction steps generated by the V2 TypeScript pipeline.
3. Every operation, symbol, and constant is verified against a strict finite allowlist.
4. All symbols are instantiated with real=True to enforce real-valued geometry.
5. Real root semantics: Odd roots of negative bases evaluate to real numbers via sp.real_root.
6. Domain obligations and equations are preserved separately from automatic simplifications.
7. Pure JSON-serializable outputs; PyProxy objects must be destroyed in JS callers.
8. Bounded Portfolio of General Symbolic Strategies:
   - Safe preprocessing, trivial contradiction & degeneracy detection
   - Linear systems (affine planes intersection, lines, coincident 2D overlap)
   - Plane-conic and structured quadric strategies (plane-sphere, cylinder-plane)
   - Quadric-quadric reduction (elimination of shared quadratic parts to plane-conic)
   - Coordinate parameterization & substitution (x=t, y=t, z=t with domain and box clipping)
   - Rigorous candidate certification, deterministic ranking, and transformation recording
"""

import json
import math
import time
import sympy as sp

# Supported constant mapping
ALLOWED_CONSTANTS = {
    'pi': sp.pi,
    'E': sp.E,
}

# Allowlisted symbol names for Cartesian coordinates and parameter
x, y, z = sp.symbols('x y z', real=True)
t = sp.Symbol('t', real=True)

ALLOWED_SYMBOLS = {'x': x, 'y': y, 'z': z, 't': t}

DEFAULT_BOUNDS = {
    'minX': -1000, 'maxX': 1000,
    'minY': -1000, 'maxY': 1000,
    'minZ': -1000, 'maxZ': 1000
}


def normalize_bounds(b):
    if isinstance(b, dict):
        return [
            b.get('xMin', b.get('minX', -1000)),
            b.get('xMax', b.get('maxX', 1000)),
            b.get('yMin', b.get('minY', -1000)),
            b.get('yMax', b.get('maxY', 1000)),
            b.get('zMin', b.get('minZ', -1000)),
            b.get('zMax', b.get('maxZ', 1000)),
        ]
    return list(b)


def build_step(step):
    """
    Recursively constructs a SymPy expression tree from a validated SymPyConstructionStep.
    Raises ValueError on any unsupported operator or invalid structure.
    """
    if not isinstance(step, dict):
        raise ValueError(f"Invalid construction step: expected dict, got {type(step).__name__}")

    op = step.get('op')
    if not op or not isinstance(op, str):
        raise ValueError("Construction step missing 'op' property")

    if op == 'Integer':
        val_str = str(step.get('value', '0'))
        return sp.Integer(int(val_str))

    elif op == 'Rational':
        num_str = str(step.get('num', '0'))
        den_str = str(step.get('den', '1'))
        den = int(den_str)
        if den == 0:
            raise ValueError("Zero denominator in Rational construction step")
        return sp.Rational(int(num_str), den)

    elif op == 'Symbol':
        name = step.get('name')
        if not isinstance(name, str) or name not in ALLOWED_SYMBOLS:
            raise ValueError(f"Disallowed or unknown symbol: {name}")
        return ALLOWED_SYMBOLS[name]

    elif op == 'Constant':
        name = step.get('name')
        if not isinstance(name, str) or name not in ALLOWED_CONSTANTS:
            raise ValueError(f"Disallowed or unknown constant: {name}")
        return ALLOWED_CONSTANTS[name]

    # Operator node handling
    args_raw = step.get('args')
    if not isinstance(args_raw, list):
        raise ValueError(f"Operator step '{op}' must contain 'args' list")

    args = [build_step(a) for a in args_raw]

    if op == 'Add':
        return sp.Add(*args)

    elif op == 'Mul':
        return sp.Mul(*args)

    elif op == 'Pow':
        if len(args) != 2:
            raise ValueError(f"Pow operator requires exactly 2 arguments, got {len(args)}")
        base, exp = args[0], args[1]
        # Real root compatibility:
        # SymPy's default sp.Pow(-8, 1/3) evaluates to complex 1 + sqrt(3)*I on the principal branch.
        # In real-valued geometry, an odd root of a real number is uniquely real.
        if isinstance(exp, sp.Rational) and exp.q % 2 != 0:
            return sp.real_root(base, exp.q) ** exp.p
        return sp.Pow(base, exp)

    elif op == 'Sqrt':
        if len(args) != 1:
            raise ValueError(f"Sqrt operator requires exactly 1 argument, got {len(args)}")
        return sp.sqrt(args[0])

    elif op == 'Root':
        if len(args) != 2:
            raise ValueError(f"Root operator requires exactly 2 arguments (radicand, index), got {len(args)}")
        radicand, index = args[0], args[1]
        if isinstance(index, sp.Integer) and index % 2 != 0:
            return sp.real_root(radicand, int(index))
        elif isinstance(index, sp.Rational) and index.p % 2 != 0:
            inv = sp.Pow(index, -1)
            if isinstance(inv, sp.Rational) and inv.q % 2 != 0:
                return sp.real_root(radicand, inv.q) ** inv.p
        return sp.Pow(radicand, sp.Pow(index, -1))

    elif op == 'Abs':
        if len(args) != 1:
            raise ValueError("Abs operator requires exactly 1 argument")
        return sp.Abs(args[0])

    elif op == 'Sin':
        return sp.sin(args[0])
    elif op == 'Cos':
        return sp.cos(args[0])
    elif op == 'Tan':
        return sp.tan(args[0])
    elif op == 'Sec':
        return sp.sec(args[0])
    elif op == 'Csc':
        return sp.csc(args[0])
    elif op == 'Cot':
        return sp.cot(args[0])

    elif op == 'ArcSin':
        return sp.asin(args[0])
    elif op == 'ArcCos':
        return sp.acos(args[0])
    elif op == 'ArcTan':
        return sp.atan(args[0])

    elif op == 'Sinh':
        return sp.sinh(args[0])
    elif op == 'Cosh':
        return sp.cosh(args[0])
    elif op == 'Tanh':
        return sp.tanh(args[0])

    elif op == 'Exp':
        return sp.exp(args[0])
    elif op == 'Log':
        return sp.log(args[0])

    elif op == 'Eq':
        if len(args) != 2:
            raise ValueError("Eq operator requires exactly 2 arguments")
        return sp.Eq(args[0], args[1])

    else:
        raise ValueError(f"Unsupported construction operator: '{op}'")


def build_surface(plan):
    """
    Constructs SymPy objects for a single surface plan, producing serializable summary data.
    """
    if not isinstance(plan, dict):
        raise ValueError("Surface plan must be a dict")

    target = plan.get('target')
    if target != 'sympy':
        raise ValueError(f"Unsupported plan target: {target}")

    eq_step = plan.get('equation')
    if not eq_step or eq_step.get('op') != 'Eq':
        raise ValueError("Invalid equation step: expected Eq relation")

    lhs_expr = build_step(eq_step['args'][0])
    rhs_expr = build_step(eq_step['args'][1])
    equation = sp.Eq(lhs_expr, rhs_expr)

    residual = lhs_expr - rhs_expr
    simplified_residual = sp.simplify(residual)

    free_syms = sorted([s.name for s in residual.free_symbols if isinstance(s, sp.Symbol)])
    symbols_sp = [ALLOWED_SYMBOLS[name] for name in free_syms if name in ALLOWED_SYMBOLS]

    raw_conditions = plan.get('domainConditions', [])
    domain_conditions = []
    for cond in raw_conditions:
        c_step = cond.get('condition')
        c_expr = build_step(c_step) if c_step else None
        kind = cond.get('kind', 'unknown')
        c_str = str(c_expr) if c_expr is not None else ''

        domain_conditions.append({
            'id': cond.get('id', ''),
            'kind': kind,
            'conditionStr': c_str,
            'description': cond.get('description', ''),
        })

    is_poly = False
    degree = None
    if symbols_sp:
        try:
            is_poly = bool(residual.is_polynomial(*symbols_sp))
            if is_poly:
                degree = int(sp.total_degree(residual, *symbols_sp))
        except Exception:
            is_poly = False
            degree = None
    elif residual.is_number:
        is_poly = True
        degree = 0

    is_identity = bool(residual == 0 or simplified_residual == 0)
    is_contradiction = bool(residual.is_number and residual != 0)

    return {
        'equationStr': str(equation),
        'lhsStr': str(lhs_expr),
        'rhsStr': str(rhs_expr),
        'residualStr': str(residual),
        'simplifiedResidualStr': str(simplified_residual),
        'variables': free_syms,
        'domainConditions': domain_conditions,
        'isPolynomial': is_poly,
        'degree': degree,
        'isConstantIdentity': is_identity,
        'isConstantContradiction': is_contradiction,
    }


def prepare_system_json(json_str):
    """
    Main entry point for Phase V3 expression analysis.
    """
    data = json.loads(json_str)
    plan_f = data.get('surfaceF')
    plan_g = data.get('surfaceG')

    if not plan_f or not plan_g:
        raise ValueError("Payload must contain both 'surfaceF' and 'surfaceG' plans")

    res_f = build_surface(plan_f)
    res_g = build_surface(plan_g)

    joint_vars = sorted(list(set(res_f['variables']).union(set(res_g['variables']))))
    total_domain_conds = len(res_f['domainConditions']) + len(res_g['domainConditions'])
    has_identity = res_f['isConstantIdentity'] or res_g['isConstantIdentity']
    has_contradiction = res_f['isConstantContradiction'] or res_g['isConstantContradiction']

    summary = {
        'surfaceF': res_f,
        'surfaceG': res_g,
        'systemVariables': joint_vars,
        'totalDomainObligations': total_domain_conds,
        'hasIdentity': has_identity,
        'hasContradiction': has_contradiction,
    }

    return json.dumps(summary)


# ==============================================================================
# Phase V4: Exact Intersection Engine Helpers & Strategies
# ==============================================================================

def safe_numeric_approx(expr):
    """Safely converts exact expression to float approximation."""
    try:
        val = float(expr.evalf())
        if math.isnan(val) or math.isinf(val):
            return None
        return val
    except Exception:
        return None

def make_finite_endpoint(expr, approx=None):
    if approx is None:
        approx = safe_numeric_approx(expr)
    return {
        'kind': 'finite',
        'exact': str(expr),
        'numericApprox': approx
    }

def make_infinite_endpoint(sign):
    return {
        'kind': 'infinite',
        'sign': sign
    }

def make_interval(min_ep, min_inc, max_ep, max_inc):
    return {
        'min': min_ep,
        'minInclusive': min_inc if min_ep['kind'] == 'finite' else False,
        'max': max_ep,
        'maxInclusive': max_inc if max_ep['kind'] == 'finite' else False,
    }
